### ISSUE TITLE
Cluster a9332b33: NPE in CalculatorModel.getDefaultLpFromPreferences()

### ISSUE THREAD

**Issue by amicloud** [wsmithsrs/SideDeckRewrite#8]
https://play.google.com/apps/publish/?dev_acc=04688425850747899995#AndroidMetricsErrorsPlace:p=com.outplaysoftworks.sidedeck&appVersion=PRODUCTION&clusterName=apps/com.outplaysoftworks.sidedeck/clusters/a9332b33

**Comment by wsmithsrs** [comment]
Think I have this one knocked out
